### ISSUE TITLE
Standardise the names and descriptions of languages buildpacks in the builder

### ISSUE THREAD

**Issue by edmorley** [heroku/cnb-builder-images#408]
Currently there's a bit of inconsistency in the "Name" shown for each buildpack in the builder:

```
$ pack builder inspect heroku/builder:22
...
Buildpacks:
 ID                               NAME                              VERSION       HOMEPAGE
 heroku/go                        Heroku Go                         0.1.10        https://github.com/heroku/buildpacks-go
 heroku/gradle                    Gradle                            3.2.1         https://github.com/heroku/buildpacks-jvm
 heroku/java                      Java                              3.2.1         https://github.com/heroku/buildpacks-jvm
 heroku/jvm                       Heroku OpenJDK Buildpack          3.2.1         https://github.com/heroku/buildpacks-jvm
 heroku/maven                     Maven                             3.2.1         https://github.com/heroku/buildpacks-jvm
 heroku/nodejs                    Node.js                           1.1.7         https://github.com/heroku/buildpacks-nodejs
 heroku/nodejs-corepack           Heroku Node.js Corepack           1.1.7         https://github.com/heroku/buildpacks-nodejs
 heroku/nodejs-engine             Heroku Node.js Engine             1.1.7         https://github.com/heroku/buildpacks-nodejs
 heroku/nodejs-npm                NPM Buildpack                     1.1.7         https://github.com/heroku/buildpacks-nodejs
 heroku/nodejs-pnpm-install       Heroku Node.js pnpm install       1.1.7         https://github.com/heroku/buildpacks-nodejs
 heroku/nodejs-yarn               Heroku Node.js Yarn               1.1.7         https://github.com/heroku/buildpacks-nodejs
 heroku/php                       PHP                               0.1.1         https://github.com/heroku/buildpacks-php
 heroku/procfile                  Procfile                          2.0.1         https://github.com/heroku/procfile-cnb
 heroku/python                    Python                            0.7.1         https://github.com/heroku/buildpacks-python
 heroku/ruby                      Ruby                              2.1.0         https://github.com/heroku/buildpacks-ruby
 heroku/sbt                       sbt                               3.2.1         https://github.com/heroku/buildpacks-jvm
 heroku/scala                     Scala                             3.2.1         https://github.com/heroku/buildpacks-jvm
```

Specifically:
- some prefix the name with "Heroku", others don't
- some include the word "buildpack", others don't

In addition, we should perhaps try and distinguish between the composite buildpacks (formerly meta buildpacks) and the component buildpacks in the name.

These names come from the `name` field in `buildpack.toml`, e.g.:
https://github.com/heroku/procfile-cnb/blob/0574174d9634f0a4fed940efbb584b050dec30fc/buildpack.toml#L6

Whilst improving these, we should also audit the `description` fields, e.g.:
https://github.com/heroku/procfile-cnb/blob/0574174d9634f0a4fed940efbb584b050dec30fc/buildpack.toml#L8

...since the descriptions vary quite a bit too, and they are shown on e.g. the buildpack registry:
https://registry.buildpacks.io/buildpacks/heroku/procfile

The current descriptions are:

```
$ rg 'description = ' buildpacks*/**/buildpack.toml
buildpacks-ruby/buildpacks/ruby/buildpack.toml
8:description = "Official Heroku buildpack for using Ruby to target Cloud Native Buildpack (CNB) builds."

buildpacks-python/buildpack.toml
8:description = "Heroku's official Python Cloud Native Buildpack."

buildpacks-php/buildpacks/php/buildpack.toml
8:description = "Heroku's official PHP Cloud Native Buildpack."

buildpacks-jvm/meta-buildpacks/scala/buildpack.toml
8:description = "Official Heroku buildpack for Scala applications."

buildpacks-jvm/meta-buildpacks/java/buildpack.toml
8:description = "Official Heroku buildpack for Java applications."

buildpacks-jvm/buildpacks/sbt/buildpack.toml
9:description = "Official Heroku buildpack for sbt applications."

buildpacks-jvm/buildpacks/maven/buildpack.toml
9:description = "Official Heroku buildpack for Maven applications."

buildpacks-jvm/buildpacks/gradle/buildpack.toml
9:description = "Official Heroku buildpack for Gradle applications."

buildpacks-jvm/buildpacks/jvm/buildpack.toml
8:description = "Official Heroku buildpack for installing OpenJDK"
```

The following CNBs are missing a description:

```
$ rg --files-without-match '^description\s*=\s*' buildpacks*/**/buildpack.toml | sort
buildpacks-go/buildpack.toml
buildpacks-jvm/buildpacks/jvm-function-invoker/buildpack.toml
buildpacks-jvm/meta-buildpacks/java-function/buildpack.toml
buildpacks-nodejs/buildpacks/nodejs-corepack/buildpack.toml
buildpacks-nodejs/buildpacks/nodejs-engine/buildpack.toml
buildpacks-nodejs/buildpacks/nodejs-function-invoker/buildpack.toml
buildpacks-nodejs/buildpacks/nodejs-npm-engine/buildpack.toml
buildpacks-nodejs/buildpacks/nodejs-npm-install/buildpack.toml
buildpacks-nodejs/buildpacks/nodejs-pnpm-install/buildpack.toml
buildpacks-nodejs/buildpacks/nodejs-yarn/buildpack.toml
buildpacks-nodejs/buildpacks/npm/buildpack.toml
buildpacks-nodejs/meta-buildpacks/nodejs-function/buildpack.toml
buildpacks-nodejs/meta-buildpacks/nodejs/buildpack.toml
```

GUS-W-14121598.

**Comment by edmorley** [comment]
I think we should:
- Always prefix the name with "Heroku" (given that in the CNB world buildpacks can be from a variety of vendors)
- Not use the word "buildpack" since it's redundant
- Try to distinguish between composite and component buildpacks by having the component buildpacks use a semicolin prefix. ie: `Heroku <Lang>` for the composite and `Heroku <Lang>: <Some component>` for the component.

**Comment by edmorley** [comment]
For `description`, the only place this is used as far as I can see is the CNB registry - however, that's still an important use-case. I think we should:
- Add descriptions to any buildpack that is currently missing them
- Remove the phrase "Official" since it's redundant given these buildpacks are under the `heroku` namespace, plus it sounds a bit over the top IMO
- Consistently use the term "buildpack" rather than "cloud native buildpack" (since all of the buildpacks on the CNB registry are CNBs)
- Label component buildpacks in such a way that people don't accidentally use them without meaning to

**Comment by edmorley** [comment]
For `keywords`, I think we should:
- Always include `"heroku"`
- Make sure the composite buildpacks include any notable keywords for component buildpacks they contain. eg: The Java composite buildpack should probably include the "maven" keyword too, given one of its component buildpacks is for Maven support
- Not spam dozens of keywords, but pick the most common

**Comment by Malax** [comment]
> * Try to distinguish between composite and component buildpacks by having the component buildpacks use a semicolin prefix. ie: `Heroku <Lang>` for the composite and `Heroku <Lang>: <Some component>` for the component.

This will be hard to do correctly for some of the more polyglot ecosystems such as JVM, CLR and Node. Gradle for example is used with various languages and we therefore can't associate it with a single `Heroku <Lang>` prefix.

We could loosen this up a bit and make it a `Heroku <Ecosystem>` prefix which in some cases such as Python will be the same as the language, basically what we're already doing with the monorepo names: `buildpacks-jvm` vs `buildpacks-python`.

Apart from this small bit, I'm 👍🏻 on the proposals so far. :)

**Comment by edmorley** [comment]
Yeah agree about the prefix being harder to do in some ecosystems.

> Label component buildpacks in such a way that people don't accidentally use them without meaning to

After speaking with Manuel, we settled on descriptions like this for composite buildpacks:

`Heroku's buildpack for Java applications.`

vs this for component buildpacks (that aren't standalone in their own right):

`Heroku's Maven buildpack. A component of the 'heroku/java' buildpack.`

**Comment by edmorley** [comment]
Opened:
- https://github.com/heroku/buildpacks-go/pull/178
- https://github.com/heroku/buildpacks-jvm/pull/603
- https://github.com/heroku/buildpacks-nodejs/pull/692
- https://github.com/heroku/buildpacks-php/pull/57
- https://github.com/heroku/buildpacks-python/pull/135
- https://github.com/heroku/buildpacks-ruby/pull/223
- https://github.com/heroku/procfile-cnb/pull/189
